
#############################################################################
###                                  Grafana                              ### 
#############################################################################

- name: Installation multiple packages
  yum:
    name: net-tools
    state: present

- name: Install grafana pkgs
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
    - "https://dl.grafana.com/oss/release/grafana-5.4.2-1.x86_64.rpm"

- name: Configure Grafana
  template: 
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Configure prometheus_ds.yml
  template: 
    src: prometheus_ds.yml.j2
    owner: root
    group: grafana
    mode: 0640
    dest: "/etc/grafana/provisioning/datasources/prometheus_ds.yml"

- name: Configure sample.yaml
  template: 
    src: sample.yaml.j2
    owner: root
    group: grafana
    mode: 0640
    dest: "/etc/grafana/provisioning/dashboards/sample.yaml"

- name: Import custom dashbaords
  copy: 
    src: "{{ item }}"
    owner: root
    group: grafana
    mode: 0640
    dest: "/etc/grafana/provisioning/dashboards/"
  with_items:
   - PrometheusCustom.json
   - PrometheusSystem.json
   - DockerMonitoring.json

- name: Ensure group "node_exporter" exists
  group:
    name: node_exporter
    state: present

- name: Add the user 'node_exporter' with a bash shell
  user:
    name: node_exporter
    shell: /bin/bash
    groups: node_exporter
    append: yes

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /opt/
    owner: node_exporter
    group: node_exporter
    mode: 0775

- name: Extract node_exporter-0.17.0.linux-amd64.tar.gz into /opt/
  unarchive:
    src: /opt/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /opt/
    owner: node_exporter
    group: node_exporter
    remote_src: yes 

- name: Change name of directory 'node_exporter'
  command: mv /opt/node_exporter-0.17.0.linux-amd64 /opt/node_exporter 

- name: Creating node_exporter.service
  file:
    path: /etc/systemd/system/node_exporter.service
    state: touch
    mode: 0775

- name: Add configuration to /etc/systemd/system/node_exporter.service
  blockinfile:
    dest: /etc/systemd/system/node_exporter.service
    insertafter: EOF
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      ExecStart=/opt/node_exporter/node_exporter

      [Install]
      WantedBy=default.target

- name: Starting services Grafana
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - 'grafana-server'
    - 'node_exporter'
