
#############################################################################
###                           Author: Dorian Dinh Xuan                    ### 
###                           Date:      13.03.2019                       ###
#############################################################################

- hosts: all
  become: true
  become_user: root

  roles:
    - ghostApp

  tasks:
    - name:
      command: /home/vagrant/ghost/migrations-db.sh
      run_once: True
