version: "2.3"

services:
  mysql:
    container_name: ghost_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "ghost"
    volumes:
      - /home/vagrant/ghost/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
        - ghost-network

  ghost:
    container_name: ghostapp
    image: ghost:1.25-alpine
    restart: always
    ports:
      - 80:2368
    volumes:
      - /home/vagrant/ghost/config.production.json:/var/lib/ghost/config.production.json
      - /home/vagrant/ghost/content:/var/lib/ghost/content
    environment:
      database__client: "mysql"
      database__connection__host: "mysql"
      database__connection__user: "root"
      database__connection__password: "ghost"
      database__connection__database: "ghost"
    links:
      - mysql
    depends_on: [mysql]
    networks:
        - ghost-network
  
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    userns_mode: host
    ports:
     - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    privileged: true
    restart: always
    depends_on: [mysql, ghost]
    links:
      - mysql
      - ghost
    networks:
        - ghost-network

networks:
  ghost-network:
    driver: bridge






  
  
    
    
    
