{
 "title": "Prometheus-custom",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Active Appenders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{job=\"prometheus\"})",
     "legendFormat": "active_appenders"
    },
    {
     "expr": "sum(process_open_fds{job=\"prometheus\"})",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"prometheus\"})",
     "legendFormat": "p8s process resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "Rule Group Eval Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_sd_triton_refresh_failures_total{job=\"prometheus\"}[5m])",
     "legendFormat": "missed"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"prometheus\"}[5m])",
     "legendFormat": "iterations"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=\"prometheus\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  }
 ]
}